### ISSUE TITLE
Installation scripts in /usr/local/bin/

### ISSUE THREAD

**Issue by knutfrode** [NOAA-ORR-ERD/OilLibrary#10] opened 2017-09-07 10:37 UTC
I wonder if there is a bug in the new setup, at least I got this error message:

```Finished processing dependencies for oil-library==1.0.6
Calling /usr/bin/initialize_OilLibrary_db
Traceback (most recent call last):
  File "setup.py", line 151, in <module>
    call(db_init_script_path())
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

However, if I manually run afterwards ```/usr/local/bin/initialize_OilLibrary_db```, then installation completes as normal. 
Thus it seems like ```/local/``` is missing in the path here.

**Comment by ChrisBarker-NOAA** [comment] 2017-09-07 16:44
INteresting, that path is generated like so:

```
def db_init_script_path():
    return os.path.join(sys.prefix, 'bin', db_init_script_name)
```
and sys.prefix is:

"""
sys.prefix:

A string giving the site-specific directory prefix where the platform independent Python files are installed; by default, this is the string '/usr/local'.  ...
"""
Essentially, it is where the python is installed that is currently running, so if you are runngn a python in usr//local/, then that's what it should be set to.

How is your python installed?

Perhaps it is a system python (/usr), but set up so that user-installed packages go into /usr/local. IF so then we need to find a better way to find the executable install path.

Perhaps: ``distutils.sysconfig.get_config_var('exec_prefix')``

@knutfrode: could try running that on your system and see what you get?

``distutils.sysconfig.get_config_vars()``

will show you other options...

Otherwise, we should maybe call the python module directly, rather as an external script.

**Comment by ChrisBarker-NOAA** [comment] 2017-09-07 16:47
@JamesMakela:

Would a simple:

```
oil_library.initializedb.make_db()
```
work?

**Comment by JamesMakela-NOAA** [comment] 2017-09-07 17:32
@ChrisBarker-NOAA: I think the problem that we were trying to solve when we made this a post-processing script is the location of the database when it is built.  When you perform `setup.py develop`, it is correct because site-packages contains a link to the sources.  But when you perform `setup.py install`, the database would be incorrectly built inside the sources instead of the installation area inside site-packages.  I could revisit this and see if I can get it working without the post-processing.

@knutfrode: This is very strange behavior, not what I would expect.  Do you have two Python installations on your system?  On the command line, are you entering `setup.py <target>` or are you entering `python setup.py <target>`?  I personally like specifying the python that I am using, which will use the one found by my system $PATH.  But it really should work either way.

**Comment by ChrisBarker-NOAA** [comment] 2017-09-07 19:32
@JamesMakela:

I tried this out, having setup.py call make_db directly.

This required a hack to remove the current working dir from sys.path, so the installed version would be imported.

But it seems to work, at least with both "install" and "develop" on my machine.

It's in the "call_init_directly" branch in our internal repo.

-CHB

**Comment by knutfrode** [comment] 2017-09-07 20:17
Ok, perhaps this problem is related to the fact that I was never able to install with ```python setup.py develop``` (as I would like to), but had to do ```sudo python setup.py install```

With ```develop``` it tries to install to ```/usr/local/lib/python2.7/dist-packages/``` where sudo-access is needed. But when adding "sudo",  the problem is again that it tries to call ```/usr/bin/initialize_OilLibrary_db``` which does not exits.

Btw, ```sys.prefix``` is simply ```/usr```
This is Ubuntu, and the same issue on two machines (laptop and stationary). There is only one Python installation (2.7) on both machines.

**Comment by JamesMakela-NOAA** [comment] 2017-09-07 22:40
@knutfrode: Ok, I think I see what's happening.  When you perform sudo, you are assuming the admin users environment, including the $PATH environment.  If you are required to sudo, then maybe specifying the entire path like this: `/usr/local/bin/python setup.py <target>` will work.  Let me know what happens.

@ChrisBarker-NOAA: That sounds very promising.  I will check out the branch and see.

**Comment by knutfrode** [comment] 2017-09-07 22:45
There is no Python in my ```/usr/local/bin/```, only in ```/usr/bin``` (and prefix makes no difference).

But yes, I would like to avoid using ```sudo``` at all, if possible.

**Comment by ChrisBarker-NOAA** [comment] 2017-09-08 02:32
Knut-Frode:

What does:

distutils.sysconfig.get_config_vars()

Show for you?

I think the problem is that your python is configured to install user
packages somewhere other than sys.prefix

-CHB

Sent from my iPhone

On Sep 7, 2017, at 3:45 PM, Knut-Frode Dagestad <notifications@github.com>
wrote:

There is no Python in my /usr/local/bin/, only in /usr/bin (and prefix
makes no difference).

But yes, I would like to avoid using sudo at all, if possible.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NOAA-ORR-ERD/OilLibrary/issues/10#issuecomment-327947276>,
or mute the thread

**Comment by knutfrode** [comment] 2017-09-08 07:09
On my machines ```disutils``` has no module ```sysconfig```, so it has to be imported as ```import sysconfig```

```sysconfig.get_config_var('exec_prefix')``` gives ```/usr```, same as ```sys.prefix```

```sysconfig.get_config_vars()``` gives a very long output. I could post the whole thing if it can help.

**Comment by ChrisBarker-NOAA** [comment] 2017-09-08 19:20
@knutfrode: 

>On my machines disutils has no module sysconfig, so it has to be imported as import sysconfig

sorry -- I accidentally was testing with a py3 environmnet.

But bingo! on py2, I found:

sysconfig.get_paths(), which on my machine (with a conda root install), is:

```
In [7]: sysconfig.get_paths()
Out[7]: 
{'data': '/Users/chris.barker/miniconda2',
 'include': '/Users/chris.barker/miniconda2/include/python2.7',
 'platinclude': '/Users/chris.barker/miniconda2/include/python2.7',
 'platlib': '/Users/chris.barker/miniconda2/lib/python2.7/site-packages',
 'platstdlib': '/Users/chris.barker/miniconda2/lib/python2.7',
 'purelib': '/Users/chris.barker/miniconda2/lib/python2.7/site-packages',
 'scripts': '/Users/chris.barker/miniconda2/bin',
 'stdlib': '/Users/chris.barker/miniconda2/lib/python2.7'}
```

I think `sysconfig.get_paths()['scripts']` is what we are looking for.

what value does it have on your system?

-CHB

**Comment by knutfrode** [comment] 2017-09-08 19:26
On my machines (and probably on the Travis machine) this gives ```/usr/local/bin```
This is ubuntu, and packages are installed with apt-get or pip, not conda.

**Comment by ChrisBarker-NOAA** [comment] 2017-09-08 19:34
awesome! I think we found it.

so, in setup.py, change line 22 from:

```return os.path.join(sys.prefix, 'bin', db_init_script_name)```

to

```
import sysconfig
return sysconfig.get_paths()['scripts']
```
and you should be good to go.

We'll patch master, too, but this can get you going in the meantime.

**Comment by ChrisBarker-NOAA** [comment] 2017-09-08 19:44
@JamesMakela: 

Suggested patch pushed to gitLab master.

Though I still think it may be better to use the direct call approach.

**Comment by JamesMakela-NOAA** [comment] 2017-09-14 23:53
@knutfrode: Ok, I believe we have finally got a setup.py that will work for all the targets that we use.  It is now checked into master.  Try it out and see if this fixes your problem.

One thing though about installing on the system Python install via sudo.  I found that all the temp files that setuptools creates are owned by root.root.  So when getting the new master updates, it would be a good idea to perform `sudo pip uninstall oil_library; sudo python setup.py cleanall`, and then run `sudo python setup.py install`.

**Comment by knutfrode** [comment] 2017-09-18 11:25
After uninstalling/cleanall, I now reinstalled with
```python setup.py develop --user``` to avoid needing sudo-rights.
This worked fine, and the reported problem seems now to be fixed.

**Comment by frq0224** [comment] 2018-09-07 03:29
thanks.
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    repo = Repo('.')
  File "C:\ProgramData\Anaconda2\lib\site-packages\git\repo\base.py", line 168,
in __init__    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: C:\Users\frqIntel\Desktop\lunwen\gnome\OilLibrary

**Comment by ChrisBarker-NOAA** [comment] 2018-09-07 07:44
Next time, please open a new issue for a new problem.

But for now, this is because we are trying to get the date of the last update from git, and it won't work if building from a no valid git repo. I am fixing that now -- stay tuned.

**Comment by ChrisBarker-NOAA** [comment] 2018-09-07 08:31
I've pt out a new release -- it should work now.

**Closed by ChrisBarker-NOAA** 2018-09-07 08:31 UTC
